* usr/bin/zEscrow:   - support taking a zEscrow server name as arg1   - support taking a wrapping passphrase on stdin   - auto-retry uploads to the server up to 30 times   - when non-interactive, print "URL: %s" as last line     for machine consumption

diff --git a/usr/bin/zEscrow b/usr/bin/zEscrow
--- a/usr/bin/zEscrow
+++ b/usr/bin/zEscrow
@@ -29,9 +29,6 @@ error() {
 
 PKG="zEscrow"
 
-# Store the stty, which we modify later
-stty_orig=$(stty -g)
-
 # Bail out early, if this isn't an ecryptfs setup
 if [ ! -f "$HOME/.ecryptfs/wrapped-passphrase" ] || [ ! -f "$HOME/.ecryptfs/Private.sig" ]; then
 	error "Unable to find eCryptfs configuration at [$HOME/.ecryptfs/]"
@@ -41,9 +38,11 @@ fi
 tempfile=$(mktemp --tmpdir=/dev/shm $PKG-XXXXXXXXXXXX.tar.gz.gpg)
 tempdir=$(mktemp -d /dev/shm/$PKG-XXXXXXXXXXXX)
 gpg_dir=$(mktemp -d /dev/shm/$PKG-XXXXXXXXXXXX)
-trap "(stty $stty_orig; rm -rf $tempfile $tempdir $gpg_dir 2>/dev/null) || true" EXIT HUP INT QUIT TERM
+trap "(rm -rf $tempfile $tempdir $gpg_dir 2>/dev/null) || true" EXIT HUP INT QUIT TERM
 
-echo "
+if [ -z "$1" ]; then
+	# No server specified, prompt interactively
+	echo "
 #####################################################################
 # Some eCryptfs users choose to store a backup of of their eCryptfs
 # configuration and their randomly generated MOUNT passphrase on an
@@ -66,12 +65,15 @@ echo "
 # securely retrieve your escrowed data later!
 #####################################################################
 "
-
-# Get the zEscrow server
-# NOTE: Use lower case "e" here, messes with SSL cert
-default_server="https://zescrow.gazzang.com"
-printf "Key escrow server [$default_server]: "
-server=$(head -n1)
+	# Get the zEscrow server
+	# NOTE: Use lower case "e" here, messes with SSL cert
+	default_server="https://zescrow.gazzang.com"
+	printf "Key escrow server [$default_server]: "
+	server=$(head -n1)
+else
+	# Looks like we got a server as a command argument
+	server="$1"
+fi
 [ -n "$server" ] || server="$default_server"
 
 # Ensure SSL
@@ -98,8 +100,9 @@ rm -f "$tempdir/ecryptfs/wrapped-passphrase"
 touch "$tempdir/ecryptfs/unwrapped-passphrase"
 chmod 600 "$tempdir/ecryptfs/unwrapped-passphrase"
 
-# Prompt for login passphrase
-echo "
+if [ -t 0 ]; then
+	# Interactively prompt for login passphrase
+	echo "
 #####################################################################
 # Your LOGIN passphrase is required to unwrap your randomly generated
 # MOUNT passphrase.  The key escrow server will NOT store your login
@@ -107,11 +110,19 @@ echo "
 # passphrase.
 #####################################################################
 "
-stty -echo
-printf "Your LOGIN passphrase: "
-passphrase=$(head -n1)
-stty $stty_orig
-printf "\n"
+	# Store the stty, which we modify
+	stty_orig=$(stty -g)
+	trap "(stty $stty_orig; rm -rf $tempfile $tempdir $gpg_dir 2>/dev/null) || true" EXIT HUP INT QUIT TERM
+	stty -echo
+	printf "Your LOGIN passphrase: "
+	passphrase=$(head -n1)
+	stty $stty_orig
+	printf "\n"
+else
+	# Wrapping passphrase is on stdin
+	passphrase=$(cat /dev/stdin)
+fi
+
 if !(printf "%s" "$passphrase" | ecryptfs-unwrap-passphrase "$HOME/.ecryptfs/wrapped-passphrase" - > "$tempdir/ecryptfs/unwrapped-passphrase"); then
 	error "Failed to unwrap passphrase.  Incorrect LOGIN passphrase?"
 fi
@@ -124,7 +135,14 @@ md5_1=$(tar -C "$tempdir" -zcf - "ecryptfs" | md5sum | awk '{print $1}')
 rm -rf "$tempdir" "$gpg_dir"
 
 # Push to the escrow server
-url=$(curl -s -o- -X POST --data-urlencode payload@"$tempfile" $server/deposit/index.html) || error "Failed to upload to server"
+for i in $(seq 1 30); do
+	# Auto retry for up to 30 seconds
+	if url=$(curl -s -o- -X POST --data-urlencode payload@"$tempfile" $server/deposit/index.html) && [ -n "$url" ];then
+		break
+	else
+		sleep 1
+	fi
+done
 rm -f "$tempfile"
 [ -n "$url" ] || error "Failed to upload to server"
 
@@ -133,7 +151,8 @@ md5_2=$(printf "%s" "$url" | sed -e "s:.*=::" -e "s:-.*::")
 [ "$md5_1" = "$md5_2" ] || error "Data received by server [$md5_2] does not match data sent [$md5_1]"
 
 # Finish up
-echo "
+if [ -z "$1" ]; then
+	echo "
 #####################################################################
 # To complete this escrow, you MUST go to this url, login,
 # and associate an email address with your upload IMMEDIATELY!
@@ -142,16 +161,19 @@ echo "
 #
 #####################################################################
 "
-# Launch browser?
-while true; do
-	printf "Go to [%s] now [Y/n]: " "$url"
-	answer=$(head -n1)
-	case "$answer" in
-		n*|N*)
-			exit 0
-		;;
-		Y*|y*)
-			exec sensible-browser $url
-		;;
-	esac
-done
+	# Launch browser?
+	while true; do
+		printf "Go to [%s] now [Y/n]: " "$url"
+		answer=$(head -n1)
+		case "$answer" in
+			n*|N*)
+				exit 0
+			;;
+			Y*|y*)
+				exec sensible-browser $url
+			;;
+		esac
+	done
+else
+	printf "URL: $url\n"
+fi
